### ISSUE TITLE
Missing builds

### ISSUE THREAD

**Issue by txj-xyz** [Topis-Lavalink-Plugins/Spotify-Plugin#5]
Implementing this is not working on latest build of Lavalink, can you please clarify what needs to be done?

This is currently my `application.yml` file

```
lavalink:
    plugins:
        spotify:
            clientId: 'My_Client_ID'
            clientSecret: 'My_Secret'
            countryCode: 'US'
            providers:
                - 'ytsearch:"%ISRC%"'
                - 'ytsearch:%QUERY%'
    server: { ... }
```
